version: '3.9'

services:

  backend:
    build: ./backend
    ports:
      - "8080:8080"
    command: ['python', 'main.py']
    environment:
      - DATABASE_URL=postgresql://dev_admin:dev@db:5432/daydreamers_dev
    volumes:
      - ./backend:/app

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    volumes:
      - ./frontend:/app
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy-data:/data
      - caddy-config:/config
    depends_on:
      - backend
  
  database:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=dev_admin
      - POSTGRES_PASSWORD=dev
      - POSTGRES_DB=daydreamers_dev

volumes:
  caddy-data:
  caddy-config:
  postgres-data: